Repository TeamPetP/Backend, pull requests merged in 2022-07, with the labels that each got.

#43 모임 참여자 추방, 신청 취소
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingWaitingMemberCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingWaitingMemberCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: enhancement

#44 관심 모임 api, 회원 간단 정보 추가 및 수정
  build/generated/querydsl/petPeople/pet/domain/meeting/entity/QMeetingBookmark.java
  deploy.sh
  src/main/java/petPeople/pet/controller/comment/CommentController.java
  src/main/java/petPeople/pet/controller/comment/dto/req/CommentEditReqDto.java
  src/main/java/petPeople/pet/controller/comment/dto/req/CommentWriteReqDto.java
  src/main/java/petPeople/pet/controller/comment/dto/resp/CommentEditRespDto.java
  src/main/java/petPeople/pet/controller/comment/dto/resp/CommentWriteRespDto.java
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingCreateReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingEditReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCreateRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingEditRespDto.java
  src/main/java/petPeople/pet/controller/member/MemberController.java
  src/main/java/petPeople/pet/controller/member/MemberNotificationController.java
  src/main/java/petPeople/pet/controller/member/dto/resp/MeetingJoinApplyRespDto.java
  src/main/java/petPeople/pet/controller/member/dto/resp/notificationResp/MemberMeetingBookMarkRespDto.java
  src/main/java/petPeople/pet/domain/meeting/entity/Meeting.java
  src/main/java/petPeople/pet/domain/meeting/entity/MeetingBookmark.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingBookmarkCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingBookmarkCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingBookmarkRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingWaitingMemberCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingWaitingMemberCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingWaitingMemberService.java
  src/main/java/petPeople/pet/exception/ErrorCode.java
  src/test/java/petPeople/pet/domain/meeting/service/MeetingServiceTest.java
Labels: enhancement, fix

#53 모임 단건 조회 응답값 수정
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/meeting/entity/Category.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingRetrieveOneMemberDto.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: fix

#55 FIX:FIX: 모임 가입 요청 토큰 오류 수정
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: bug, fix

#56 Develop
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: push to master

#57 FIX: 테스트 오류 수정
  src/test/java/petPeople/pet/domain/meeting/service/MeetingServiceTest.java
Labels: bug, fix

#60 FIX: 모임 API http 메서드 수정 및 securityConfig 수정
  src/main/java/petPeople/pet/config/SecurityConfig.java
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/domain/comment/entity/Comment.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/resources/application-local.yml
  src/test/java/petPeople/pet/domain/meeting/service/MeetingServiceTest.java
Labels: fix

#61 Develop
  src/main/java/petPeople/pet/config/SecurityConfig.java
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/resources/application-local.yml
Labels: push to master

#63 FIX: 게시글 및 댓글 삭제 알림 관련 오류 해결
  src/main/java/petPeople/pet/controller/post/PostController.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepository.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/petPeople/pet/domain/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/service/PostService.java
Labels: bug, fix

#64 Develop
  src/main/java/petPeople/pet/controller/post/PostController.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepository.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/petPeople/pet/domain/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/service/PostService.java
Labels: push to master

#68 FEAT: ADD 게시글 조회 시 자신의 게시글 확인 필드 추가
  src/main/java/petPeople/pet/controller/post/dto/resp/PostRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/post/service/PostService.java
Labels: enhancement, fix

#69 FEAT: MODIFY 모임 조회 시 회원 사진 추가
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingRetrieveRespDto.java
Labels: enhancement, fix

#70 Develop
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingRetrieveRespDto.java
  src/main/java/petPeople/pet/controller/post/dto/resp/PostRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/post/service/PostService.java
Labels: push to master

#73 Develop
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/controller/member/MemberController.java
  src/main/java/petPeople/pet/controller/member/dto/resp/MemberCountDto.java
  src/main/java/petPeople/pet/controller/post/PostController.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepository.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingMemberCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingMemberCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingPostService.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/java/petPeople/pet/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/petPeople/pet/domain/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/service/PostService.java
  src/main/resources/application-local.yml
Labels: push to master

#76 Develop
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/domain/meeting/entity/Meeting.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: push to master

#80 FIX: 모임 가입 취소 요청 시 500에러 확인
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: fix

#81 Develop
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/controller/member/MemberController.java
  src/main/java/petPeople/pet/controller/member/dto/resp/MeetingWaitingMemberRespDto.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingWaitingMemberService.java
Labels: push to master

#83 FEAT: 모임 이미지 조회 시 모임 이미지가 아닌 모임 게시글에 있는 모든 사진 조회
  build/generated/querydsl/petPeople/pet/domain/comment/entity/QCommentLike.java
  build/generated/querydsl/petPeople/pet/domain/meeting/entity/QMeetingImageFile.java
  src/main/java/petPeople/pet/controller/comment/dto/req/CommentWriteReqDto.java
  src/main/java/petPeople/pet/controller/comment/dto/resp/CommentWriteRespDto.java
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingCreateReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingEditReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCreateRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingEditRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingPostImageRetrieveRespDto.java
  src/main/java/petPeople/pet/controller/post/PostCommentController.java
  src/main/java/petPeople/pet/controller/post/dto/resp/CommentRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/comment/entity/CommentLike.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentLikeCustomRepository.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentLikeCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/meeting/entity/MeetingImageFile.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageFileCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageFileCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageFileRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingPostImageCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingPostImageCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/test/java/petPeople/pet/domain/comment/service/CommentServiceTest.java
  src/test/java/petPeople/pet/domain/meeting/service/MeetingServiceTest.java
Labels: enhancement, fix

#84 Develop
  build/generated/querydsl/petPeople/pet/domain/comment/entity/QCommentLike.java
  build/generated/querydsl/petPeople/pet/domain/meeting/entity/QMeetingImageFile.java
  src/main/java/petPeople/pet/controller/comment/dto/req/CommentWriteReqDto.java
  src/main/java/petPeople/pet/controller/comment/dto/resp/CommentWriteRespDto.java
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingCreateReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingEditReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCreateRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingEditRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingPostImageRetrieveRespDto.java
  src/main/java/petPeople/pet/controller/post/PostCommentController.java
  src/main/java/petPeople/pet/controller/post/dto/resp/CommentRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/comment/entity/CommentLike.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentLikeCustomRepository.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentLikeCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/meeting/entity/MeetingImageFile.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageFileCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageFileCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageFileRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingPostImageCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingPostImageCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/test/java/petPeople/pet/domain/comment/service/CommentServiceTest.java
  src/test/java/petPeople/pet/domain/meeting/service/MeetingServiceTest.java
Labels: push to master

#86 FEAT: MODIFTY 댓글 전체 조회 시 개수 추가 및 페이징 기능 삭제
  src/main/java/petPeople/pet/controller/comment/dto/req/CommentWriteReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingCreateReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingEditReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCreateRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingEditRespDto.java
  src/main/java/petPeople/pet/controller/post/PostCommentController.java
  src/main/java/petPeople/pet/controller/post/dto/resp/CommentRetrieveWithCountRespDto.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepository.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/java/petPeople/pet/util/RequestUtil.java
  src/test/java/petPeople/pet/domain/comment/service/CommentServiceTest.java
Labels: enhancement, fix

#87 Develop
  src/main/java/petPeople/pet/controller/post/PostCommentController.java
  src/main/java/petPeople/pet/controller/post/dto/resp/CommentRetrieveWithCountRespDto.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepository.java
  src/main/java/petPeople/pet/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/test/java/petPeople/pet/domain/comment/service/CommentServiceTest.java
Labels: push to master

#89 Develop
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/controller/member/dto/resp/notificationResp/NotificationMeetingJoinApprovedResponseDto.java
  src/main/java/petPeople/pet/controller/member/dto/resp/notificationResp/NotificationMeetingJoinDeclinedResponseDto.java
  src/main/java/petPeople/pet/controller/member/dto/resp/notificationResp/NotificationMeetingJoinedResponseDto.java
  src/main/java/petPeople/pet/controller/post/PostCommentController.java
  src/main/java/petPeople/pet/controller/post/PostController.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingPostImageCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingPostImageCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/java/petPeople/pet/domain/notification/entity/Notification.java
  src/main/java/petPeople/pet/domain/notification/service/NotificationService.java
  src/main/java/petPeople/pet/domain/post/repository/PostImageCustomRepository.java
  src/main/java/petPeople/pet/util/RequestUtil.java
  src/main/resources/application-local.yml
  src/test/java/petPeople/pet/domain/comment/service/CommentServiceTest.java
Labels: push to master

#90 FEAT: 미팅 대댓글 구현
  build/generated/querydsl/petPeople/pet/domain/meeting/entity/QMeetingComment.java
  build/generated/querydsl/petPeople/pet/domain/notification/entity/QNotification.java
  src/main/java/petPeople/pet/controller/meeting/MeetingCommentController.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCommentRetrieveRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCommentRetrieveWithCountRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCommentWriteRespDto.java
  src/main/java/petPeople/pet/controller/post/PostCommentController.java
  src/main/java/petPeople/pet/controller/post/dto/resp/CommentRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/comment/service/CommentService.java
  src/main/java/petPeople/pet/domain/meeting/entity/MeetingComment.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingCommentCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingCommentCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingCommentService.java
Labels: enhancement

#94 FIX: 알림 전체, 단건 삭제 시 알림 리스트 반환
  src/main/java/petPeople/pet/controller/member/MemberNotificationController.java
  src/main/java/petPeople/pet/controller/notification/NotificationController.java
  src/main/java/petPeople/pet/controller/post/dto/resp/PostWriteRespDto.java
Labels: fix

#95 Develop
  src/main/java/petPeople/pet/controller/member/MemberNotificationController.java
  src/main/java/petPeople/pet/controller/notification/NotificationController.java
  src/main/java/petPeople/pet/controller/post/dto/resp/PostWriteRespDto.java
Labels: push to master

#97 FEAT: ADD 모임 가입 신청 현황 api 조회 시 해당 모임의 현재 회원 수 필드 추가
  src/main/java/petPeople/pet/controller/member/MemberController.java
  src/main/java/petPeople/pet/controller/member/dto/resp/MeetingJoinApplyRespDto.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingWaitingMemberService.java
Labels: enhancement, fix

#99 MODIFY 회원 미팅 가입 신청 현황 api 대기중만 보기
  src/main/java/petPeople/pet/controller/post/dto/resp/PostRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingWaitingMemberCustomRepositoryImpl.java
Labels: enhancement, fix

#103 aws loadBalancer 의 타겟 그룹의 health check 를 위한 api 개발 및 cors 필터에 url 추가
  src/main/java/petPeople/pet/controller/test/TestController.java
  src/main/java/petPeople/pet/filter/CorsFilter.java
Labels: enhancement
