Repository TeamPetP/Backend, pull requests merged in 2022-08, with the labels that each got.

#106 FEAT: MODIFY 모임 신청 현황 조회 api 에 joinMembers 추가
  src/main/java/petPeople/pet/aspect/LogTraceAspect.java
  src/main/java/petPeople/pet/config/AopConfig.java
  src/main/java/petPeople/pet/controller/member/dto/resp/MeetingJoinApplyRespDto.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingWaitingMemberService.java
  src/main/java/petPeople/pet/filter/CorsFilter.java
  src/main/java/petPeople/pet/trace/TraceId.java
  src/main/java/petPeople/pet/trace/TraceStatus.java
  src/main/java/petPeople/pet/trace/logtrace/LogTrace.java
  src/main/java/petPeople/pet/trace/logtrace/ThreadLocalLogTrace.java
Labels: enhancement, fix

#109 1. 모임 인원 꽉찰 경우 모집여부를 false로, 추방 또는 탈퇴하여 모집인원이 꽉차지 않을 경우 모집여부를 true로
  src/main/java/petPeople/pet/aspect/LogTraceAspect.java
  src/main/java/petPeople/pet/config/AopConfig.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingPostRetrieveRespDto.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingPostService.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/java/petPeople/pet/trace/TraceId.java
  src/main/java/petPeople/pet/trace/TraceStatus.java
  src/main/java/petPeople/pet/trace/logtrace/LogTrace.java
  src/main/java/petPeople/pet/trace/logtrace/ThreadLocalLogTrace.java
Labels: enhancement, fix

#112 FIX: 모임 가입 요청 승인/거절 알림을 받는 대상 변경
  src/main/java/petPeople/pet/config/SecurityConfig.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingPostService.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: fix

#113 Develop
  src/main/java/petPeople/pet/config/SecurityConfig.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingPostService.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
Labels: push to master

#116 member, post, postBookrmark 엔티티 테스트 코드 작성
  src/main/java/petPeople/pet/domain/post/repository/PostCustomRepositoryImpl.java
  src/test/java/petPeople/pet/common/BaseControllerTest.java
  src/test/java/petPeople/pet/domain/member/repository/MemberRepositoryTest.java
  src/test/java/petPeople/pet/domain/post/repository/PostBookmarkRepositoryTest.java
  src/test/java/petPeople/pet/domain/post/repository/PostCustomRepositoryImplTest.java
  src/test/java/petPeople/pet/domain/post/repository/PostRepositoryTest.java
  src/test/resources/application-test.yml
Labels: test

#117 postImage, postLike, tag 엔티티 repository 계층 테스트 코드 작성
  src/main/java/petPeople/pet/domain/post/repository/PostLikeCustomRepository.java
  src/main/java/petPeople/pet/domain/post/repository/PostLikeCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/repository/TagCustomRepository.java
  src/main/java/petPeople/pet/domain/post/repository/TagCustomRepositoryImpl.java
  src/test/java/petPeople/pet/domain/post/repository/PostImageRepositoryTest.java
  src/test/java/petPeople/pet/domain/post/repository/PostLikeRepositoryTest.java
  src/test/java/petPeople/pet/domain/post/repository/TagRepositoryTest.java
Labels: test
