Repository TeamPetP/Backend, pull requests merged in 2022-05, with the labels that each got.

#3 게시글 작성, 단건조회, 수정 API 개말 및 테스트 코드 작성
  src/main/java/petPeople/pet/config/OpenEntityManagerConfig.java
  src/main/java/petPeople/pet/config/SecurityConfig.java
  src/main/java/petPeople/pet/controller/member/MemberController.java
  src/main/java/petPeople/pet/controller/member/dto/req/MemberEditReqDto.java
  src/main/java/petPeople/pet/controller/member/dto/req/MemberLocalRegisterReqDto.java
  src/main/java/petPeople/pet/controller/member/dto/req/MemberRegisterReqDto.java
  src/main/java/petPeople/pet/controller/member/dto/resp/MemberRegisterRespDto.java
  src/main/java/petPeople/pet/controller/post/PostController.java
  src/main/java/petPeople/pet/controller/post/dto/req/PostWriteReqDto.java
  src/main/java/petPeople/pet/controller/post/dto/resp/PostRetrieveRespDto.java
  src/main/java/petPeople/pet/controller/post/dto/resp/PostWriteRespDto.java
  src/main/java/petPeople/pet/domain/member/entity/Member.java
  src/main/java/petPeople/pet/domain/member/service/MemberRegisterDto.java
  src/main/java/petPeople/pet/domain/member/service/MemberService.java
  src/main/java/petPeople/pet/domain/post/entity/Post.java
  src/main/java/petPeople/pet/domain/post/entity/PostImage.java
  src/main/java/petPeople/pet/domain/post/entity/Tag.java
  src/main/java/petPeople/pet/domain/post/repository/PostCustomRepository.java
  src/main/java/petPeople/pet/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/repository/PostImageCustomRepository.java
  src/main/java/petPeople/pet/domain/post/repository/PostImageCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/repository/PostImageRepository.java
  src/main/java/petPeople/pet/domain/post/repository/PostLikeCustomRepository.java
  src/main/java/petPeople/pet/domain/post/repository/PostLikeCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/repository/PostLikeRepository.java
  src/main/java/petPeople/pet/domain/post/repository/PostRepository.java
  src/main/java/petPeople/pet/domain/post/repository/TagCustomRepository.java
  src/main/java/petPeople/pet/domain/post/repository/TagCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/post/repository/TagRepository.java
  src/main/java/petPeople/pet/domain/post/service/PostService.java
  src/test/java/petPeople/pet/domain/member/service/MemberServiceTest.java
  src/test/java/petPeople/pet/domain/post/service/PostServiceTest.java
Labels: enhancement, test

#10 미팅 도메인 개발
  src/main/java/petPeople/pet/config/SecurityConfig.java
  src/main/java/petPeople/pet/controller/meeting/MeetingController.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingCreateReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/req/MeetingEditReqDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingCreateRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingEditRespDto.java
  src/main/java/petPeople/pet/controller/meeting/dto/resp/MeetingRetrieveRespDto.java
  src/main/java/petPeople/pet/controller/post/PostController.java
  src/main/java/petPeople/pet/domain/meeting/entity/Category.java
  src/main/java/petPeople/pet/domain/meeting/entity/Meeting.java
  src/main/java/petPeople/pet/domain/meeting/entity/MeetingImage.java
  src/main/java/petPeople/pet/domain/meeting/entity/MeetingMember.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingImageRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingMemberCustomRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingMemberCustomRepositoryImpl.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/petPeople/pet/domain/meeting/repository/MeetingRepository.java
  src/main/java/petPeople/pet/domain/meeting/service/MeetingService.java
  src/main/java/petPeople/pet/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/petPeople/pet/domain/meeting/service/MeetingServiceTest.java
Labels: enhancement

#22 CICD Test
  .github/workflows/main.yml
Labels: CICD
